# Generated by Django 5.2.9 on 2026-01-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugat',
            options={'ordering': ['word']},
        ),
        migrations.AlterModelTable(
            name='lugat',
            table='Lugat',
        ),
    ]
